CREATE TABLE PLAYER (
       USERNAME VARCHAR(30) NOT NULL PRIMARY KEY,
       BALANCE_VERSION INTEGER DEFAULT 0 NOT NULL,
       BALANCE NUMERIC DEFAULT 0 NOT NULL
);

INSERT INTO PLAYER (USERNAME) VALUES ('john');
INSERT INTO PLAYER (USERNAME) VALUES ('jane');
