CREATE TABLE PLAYER (
       USERNAME VARCHAR(30) NOT NULL,
       BALANCE_VERSION INTEGER DEFAULT 0 NOT NULL,
       BALANCE NUMERIC DEFAULT 0 NOT NULL
);

INSERT INTO PLAYER (USERNAME) VALUES ('John Doe');
INSERT INTO PLAYER (USERNAME) VALUES ('Jane Doe');
